name: Test of build LLVM_runner image

on:
  pull_request:
    paths:
      - 'images/llvm_runner/Dockerfile'
      - '.github/workflows/build_llvm_runner.yml'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [matterlabs-ci-runner]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5.0.0
        with:
          push: false
          tags: "matterlabs/llvm_runner:latest"
          file: images/llvm_runner/Dockerfile
          no-cache: true
