name: Publish compiler docker image (v1.1.0) for beta testnet

on:
  workflow_dispatch:
    branches:
      - 'main'

  workflow_run:
    workflows: [Publish LLVM_runner docker image]
    types: [completed]
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, compiler]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          cd images/compiler-beta-v1.1.0
          echo "$SSH_KEY" > key.ssh
          DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain --secret id=ssh_key,src=key.ssh -t matterlabs/zksolc .
          docker push matterlabs/zksolc:v1.1.0
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
