name: Publish compiler docker image for beta testnet

on:
  workflow_dispatch:
    branches:
      - "main"

  workflow_run:
    workflows: [Publish LLVM_runner docker image]
    types: [completed]
    branches: [main]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: [self-hosted, ci-runner]

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          cd images/compiler-beta
          echo "$SSH_KEY" > key.ssh
          DOCKER_BUILDKIT=1 docker build --no-cache --progress=plain --secret id=ssh_key,src=key.ssh -t matterlabs/zksolc .
          docker push matterlabs/zksolc:latest
        env:
          SSH_KEY: ${{secrets.SSH_KEY}}
